repos:
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
    name: blacking project
    exclude: |   # do not reformat cookiecutter files
            (?x)^(
                setup.py|
                docs/conf.py|
                ([^\/]+subtasks)\/([^\/]+).py
            )$
    language_version: python3.11
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: "v0.7.1"
  hooks:
  - id: ruff
    name: ruffing sass subdirectory
    args: [--config, pyproject.toml]
    exclude: |   # lint sass subdirectory
            (?x)^((?!sass\/).*)$
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: "v0.7.1"
  hooks:
  - id: ruff
    name: ruffing tests subdirectory
    args: [--config, tests/pyproject.toml]
    exclude: |   # lint tests subdirectory
            (?x)^((?!tests\/).*)$
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: "v0.7.1"
  hooks:
  - id: ruff
    name: ruffing scripts subdirectory
    args: [--config, pyproject.toml]
    exclude: |   # lint scripts subdirectory. This is not in default cdd_quickstart.
            (?x)^((?!scripts\/).*)$
