# Experiment name and input data.
exp_name: # Name of the experiment, used to name the output directory.
synthon_file: # Synthons in the format of `data/synthons.txt`.
reaction_file: # Reactions in the format of `data/reactions.txt`.
query_molecule: # Path to the 3D conformer of query molecule, in a format compatible with OETK (e.g. sdf, oeb).
output_parent_dir: # Parent directory of the output directory.

# Directories for retrieving pre-generated data.
synthon_conf_dir: # Pre-generated synthon conformers. Required if `gen_synthon_conformers` task is skipped. 
synthon_id_map_dir: # Pre-generated mapping of synthon id to synthon SMILES.
grouped_synthon_dir: # Pre-selected synthons, organized by reactions, used to define the chemical space.
synthon_score_dir: # Pre-generated synthon scores against a specific query molecule. Required if `score_synthons` task is skipped.

limit_reactions: # Limit to certain reactions. Set to `null` to include all reactions.
synthon_limit: # Limit the number of synthons to be used for each reaction (applies to all components). Set to `null` to include all synthons for each reaction.
random_seed: # Seed for random sampling from each synthon set.
enum_isomers: true # Whether to enumerate stereoisomers during full product library enumeration.
warts_id_sep: # Separator used by FLIPPER/OMEGA.
sass_id_sep: # Separator used to join base molecule ids for naming products. Must be different from `warts_id_sep`.

tasks: [] # A set of steps to be executed by the query script. Valid steps include: ['ground_truth', 'gen_synthon_conformers', 'score_synthons', 'select_synthons', 'combine_products', 'instantiate_products', 'rescore_products'].
# ground_truth: Enumerate all products in the chemical space, generate conformers, and score against a query molecule.
# gen_synthon_conformers: Generate conformers for synthons in the chemical space.
# score_synthons: Score synthons against query fragments.
# combine_products: Select top-scoring synthon combinations, output a list of synthon id combinations.
# instantiate_products: Instantiate products based on the list of top synthon combinations.
# rescore_products: Generate conformers and score against a query molecule for products instantiated from top synthon combinations.

atom_substitution_dict: # How to substitute Enamine default connector atoms. Format: [src_atom, src_isotope, dst_atom, dst_isotope]
  - ['U', 0, 'C', 13]
  - ['Np', 0, 'C', 14]
  - ['Pu', 0, 'C', 15]
  - ['Am', 0, 'C', 16]

synthon_connectors: ['U', 'Np', 'Pu', 'Am'] # Connector atoms used in synthon files.
frag_connectors: ['He', 'Ne', 'Ar', 'Kr', 'Xe', 'Rn', 'Og'] # Connector atoms to assign to query fragments.


# Query fragmentation options
n_fragments: [2, 3] # Numbers of fragments to generate from a query.
heavy_atom_limit: 5 # Number of heavy atoms of fragments below which it will not be considered as a query fragment for matching.

# ROCS options
align_on_dummy_atom: true # Whether to enable custom color features for connector atoms.
custom_color_ff: ['[U]', '[Np]', '[Pu]', '[Am]'] # SMARTS patterns of connector atoms.
custom_color_weight: -1
custom_color_radius: 1
color_interaction_type: gaussian # 'gaussian' or 'discrete'.
scale_weight_per_atom: true # Whether to normalize the weight of color feature of each connector atom in synthons with multiple connector atoms.

cross_scoring: false # Whether to run ROCS for ring-synthons against linear fragments, and vice versa. Otherwise only run ROCS for ring-synthons against ring-fragments, linear-synthons against linear-fragments.

# OMEGA options
synthon_omega_max_conf: 50 # Max number of conf returned for each synthon.
synthon_omega_max_time: 120 # Max time allowed for conformer generation on one synthon.
synthon_omega_energy: 10 # max energy above min energy conformer allowed.
product_omega_max_conf: 500 # Max number of conf returned for each product.
product_omega_max_time: 300 # Max time allowed for conformer generation on one product.
product_omega_energy: 10
conf_file_format: oez

# Synthon selection options
top_m: 20000 # Number of products to be instantiated and scored by ROCS.
top_s_frac: 1 # Top_s fraction of synthons from each synthon-query ROCS scores to use for final product selection.
weight_factor: 0 # Factor to up-weight color_score component of the ROCS score. Currently not used.
instantiate_chunk_size: 2000 # how many isomers to put in one chunk during selected products instantiation.
