##################################################################
# LINTING
##################################################################

[tool.black]
line-length = 120

##################################################################

# The flake8 maintainers don't want to implement pyproject.toml
# support (even though this is an approved PEP)
# But by using pyproject-flake8 we can configure flake8 here
# See https://github.com/csachs/pyproject-flake8

[tool.flake8]
max-line-length = 120
exclude = ["__init__.py"]
# D401 -- First line should be in imperative mood; try rephrasing
# W503 -- Line break before binary operator (use black style)
#### flake8-annotations
# ANN101 -- Missing type annotation for self in method
# ANN102 -- Missing type annotation for cls in classmethod
# E731 -- do not assign a lambda expression, use a def
# F401 -- ignore import but unused modules
# F841 -- local variable * is assigned to but never used
# E203 -- whitespace before *. Flake8 is wrong here. Use black style.
ignore = ["D401", "F401", "W503", "ANN101", "ANN102", "E731", "F841", "E203"]

[tool.isort]
profile = 'black'
multi_line_output = 3
import_heading_stdlib = 'Standard Library'
import_heading_firstparty = 'Genentech Library'
import_heading_thirdparty = 'Third Party Library'
force_sort_within_sections = true
known_first_party = ['cdd*']